CREATE TABLE IF NOT EXISTS MovieRents
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ClientID INTEGER NOT NULL,
	MovieID INTEGER NOT NULL,
	GiveDate DATE NOT NULL,
	ReturnDate DATE,
	CHECK ((ReturnDate ISNULL) OR (ReturnDate >= GiveDate)),

	FOREIGN KEY (ClientID) REFERENCES Clients(PassportID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (MovieID) REFERENCES Movies(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Clients
(
	PassportID INTEGER PRIMARY KEY UNIQUE,
	FullName TEXT NOT NULL,
	Address TEXT NOT NULL,
	Phone INTEGER NOT NULL,

	CHECK (
		PassportID >= 0 AND
		FullName !='' AND
		Address !='' AND
		Phone !=''
	)
);

CREATE TABLE IF NOT EXISTS Movies
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL,
	Director TEXT,
	Genre TEXT,
	Starring TEXT,
	ReleaseYear INTEGER,
	Annotation TEXT,
	RentCost FLOAT NOT NULL,
	StudioID INTEGER,

	CHECK (
		RentCost > 0.0 AND
		Title !=''
	),

	FOREIGN KEY (StudioID) REFERENCES Studios(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Studios
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL,
	Country TEXT,

	CHECK (Title !='')
);